### PR TITLE
delete game button now works

### PR DESCRIPTION
**Pull request by srm00022**
This is for the issue that wanted the delete game button to be functional. The original branch I made for that one got old and I made it kind of weird when I tried to fix it, so I just made a new branch, copied what I needed to, and made sure everything still worked.
Serving still worked and I don't believe I touched any other functionality.

### CODE REVIEW

**Review by ianjackson8 — CHANGES_REQUESTED** [review]
During testing the "delete game" button removes *all* games, not the selected.
Could you fix this? Thanks!

**Comment by ianjackson8** [comment]
I also fixed a merge conflict, run `git pull` before doing any work @srm00022

**Review by ianjackson8 — APPROVED** [review]
Chef's kiss, *sehr gut*

**Comment by srm00022** [comment]
alright i pushed that branch again. I guess I was working off of something that existed in my version of main but got removed by some other work. I just put that back in, and it works as intended. Also, if I run git pull in main, create a branch and do work in it, then commit and push, it should be relatively up to date right? That's what I did for the last one, but apparently that didn't work or something

**Comment by ianjackson8** [comment]
To answer your question. If you run `gut pull` in main, that updates the code from GitHub. If you branch off of main after the pull, then *yes* your branch you created is up to date with the code.
Now, if someone makes a change and it gets merged with main, then your branch is behind by a commit. You can update your code by running `git merge main` in your branch. This takes the up to date code from the origin (GitHub) and merges it with your branch.
If you still have question, shoot me a text. This git and GitHub shit is confusing

**Pull request merged**
