### PR TITLE
Bs fix dropdown

### PR DESCRIPTION
**Pull request by bshunney**
fixed the dropdown so it can be clicked and then the choice populates the box. was having issues stylistically because I could not serve but component functions

### CODE REVIEW

**Review by ianjackson8 — CHANGES_REQUESTED** [review]
Good start. The styles need to match before getting merged to the main code.

**Comment by ianjackson8** [comment]
When you make the change, just commit the code. No need to make a new PR

**Comment by bshunney** [comment]
Sweet! Makes sense thank you.

**Review by nathanmullins11 — APPROVED** [review]
Looks good i like it. Just need to route it for the next commit

**Review by ianjackson8 — APPROVED** [review]

**Pull request merged**
